name: flutter_google_api_food
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_place: ^0.4.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: SukhumvitSet
      fonts:
        - asset: fonts/SukhumvitSet-Bold.ttf
        - asset: fonts/SukhumvitSet-Light.ttf
        - asset: fonts/SukhumvitSet-Medium.ttf
        - asset: fonts/SukhumvitSet-SemiBold.ttf
        - asset: fonts/SukhumvitSet-Text.ttf
        - asset: fonts/SukhumvitSet-Thin.ttf